# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nemanja Jevtic
title: Junior Full Stack Developer
email: p17pevt@ionio.gr
website: https://ionianironist.github.io/cv/
# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  IonianIronist
linkedin_username: nemantzia

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a software developer, currently studying Informatics at [Ionian University](https://di.ionio.gr/) and working as a fullstack developer at [epipla.com](https://www.epipla.com/).

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Fieldstalker
        link: https://github.com/leuteris99/field-stalker-public 
        link_text: Github page
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An agriculture environment monitoring prototype app
        description: | # this will include new lines to allow paragraphs
          This was a project developed for the course "Smart Environments and Applications", which is meant to be
          used for monitoring variables such as humidity, temperature, and light intensity through a WSN
          deployed in a cropland. In this project I developed the network logic for data gathering, routing and synchronization,
          as well as parsing the data and forwarding it to a remote server for visualisation.
      - layout: top-middle
        title: Recognition of epidemic cases in social web texts
        link: https://link.springer.com/chapter/10.1007/978-3-030-79157-5_36
        link_text: Springer page
        description: |
          I co-wrote the paper titled “Recognition of epidemic cases in social web texts”, which has been
          presented in Mining Humanistic Data Workshop 2021. For this project we applied ML models on
          social media text towards the detection of possible Covid19 cases.
      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Epipla.com
        link: epipla.com
        link_text: website
        sub_title: Junior Full Stack Developer
        caption: September 2021 - Present
        description: | # this will include new lines to allow paragraphs
          I have been developing statistical overview and shop administration utilities on a Joomla stack, 
          writing PHP for the backend, using a MySQL database and JavaScript with jQuery for the frontend.
          Currently, I am developing a React app designed to help with batch product editing.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ionian University
        caption: 2017 - Present
        sub_title: BSc Computer Science
        description: | # this will include new lines to allow paragraphs
          During my academic studies I aquiered the fundamental theoretical knowledge
          regarding the main concepts of computer science such as databases,
          web applications programming, embedded programming, network protocols,
          AI, IoT network architectures. The university also proved as a good start for 
          honing my technical skills with all of the programming assignments, 
          which in their own turn timely prompted me to further explore the 
          modern software development technologies.

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      General programming background: 
      - Fluent in Python, at the moment learning Django by working on a personal side-project 
      - Solid understanding of relational databases
      - Experience with low-level C/C++ programming, worked on Arduino/ZigBee IoT applications for
        environment monitoring 
      - Experience with gathering and processing of both structured and unstructured data (tabular, XML,
      sensors data, text etc.) 
      - Some experiance with Git, learning more by the day
      - Basic understanding of Docker
      - Daily-driving Debian, getting everything done from the terminal

      Look at this cool image  
      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  load_paths:
    - assets
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
